### ISSUE TITLE
Error: "Muse Bar" will damage your computer. macOS Catalina

### ISSUE THREAD

**Issue by Amir-Hass** [planecore/MuseBar#2]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/5016531/82494683-f34fb000-9ab7-11ea-8c64-4ac04fdb4401.png">

**Comment by planecore** [comment]
Do you use the latest version? v.4.2.6

**Comment by planecore** [comment]
Do you use the latest version? v4.2.6

**Comment by Amir-Hass** [comment]
Yes

**Comment by planecore** [comment]
It works perfectly fine on my machine, Muse Bar was uploaded to Apple servers they scanned it for malicious code.
Can you try to remove and download it again?

<img width="532" alt="Screen Shot 2020-05-21 at 21 18 03" src="https://user-images.githubusercontent.com/12946462/82591980-d3e48000-9ba8-11ea-92c5-5d4ea7aec775.png">

**Comment by Amir-Hass** [comment]
This time that showed. It worked thank you!
