### ISSUE TITLE
[Enhancement] Add song to playlist button

### ISSUE THREAD

**Issue by 3raxton** [planecore/MuseBar#3]
Hey, @planecore, I'm grateful that you've continued working on MuseBar as it immensely enhances Spotify's experience on my Mac.

I was thinking about enhancements and had the idea of adding the current song playing to a playlist through a button in MuseBar's second menu. Ideally, users could tap a button and see a list of their playlists, then choose a playlist to add the song to.

I've seen this done in Javascript and would be happy to share that code with you, but when it comes to Xcode, I have no idea how practical it is.  

Whether implemented or not, I'm grateful for your hard work on MuseBar! 🎉

![image](https://user-images.githubusercontent.com/20716142/83982067-07354780-a8e9-11ea-9539-9dd921ced52b.png)

**Comment by planecore** [comment]
Sounds great! I should check if Music.app scripting bridge supports this too. I want to keep the feature parity on Muse Bar between Spotify and Music.app

**Comment by 3raxton** [comment]
Ah that’s a great point, didn’t even consider it! Let me know if there’s any way I can help out with this, I’d be more than happy to do what I can.

**Comment by planecore** [comment]
Sadly in Music I can only add to library. So I think what I'll do is to add:

1. Save button: Saves the currently playing song to the user's library. Will work with Spotify and Music.
2. Add to Playlist list: Shows a list of buttons with playlists to add the currently playing song to. Will work only with Spotify.

**Comment by 3raxton** [comment]
That’s a bummer that it can’t be added to music but your alternative is perfect. Again, please let me know if there’s some way I can help you with this feature, I’d be more than happy to!

**Comment by planecore** [comment]
Awesome thanks!
