### ISSUE TITLE
Keep MuseBar context open on Touch Bar

### ISSUE THREAD

**Issue by christoff-1992** [planecore/MuseBar#7]
The Touch Bar application is only visible when the host app is in focus. This is a limitation of the Touch Bar but since this can be installed via the link attached and not the App Store private API's could be used. Pock does this https://github.com/pigigaldi/Pock.

**Comment by planecore** [comment]
Muse Bar is designed to have a minimal UI that changes only the way you control music on the Touch Bar. Muse Bar goal is not to replace the Touch Bar interface like BTT and Pock, but to enhance the experience of the regular Touch Bar.
