### ISSUE TITLE
[Bug] MuseBar missing from Control Strip

### ISSUE THREAD

**Issue by 3raxton** [planecore/MuseBar#8]
Hey there,

Up until a few days ago, MuseBar was working fairly seamlessly for me. However, now, I've encountered a bug that has caused MuseBar to behave unusually on the Touch Bar. When launching MuseBar, I run into two errors that happen in order. I'm currently using the latest version of MuseBar. The only thing I can think of that may have caused this issue was restarting ```OSDUIHelper``` within Activity Monitor, but I don't think that's the case. 

**Error 1: Holding on the Control Strip section of MuseBar makes the Preferences show** 

Expected behavior: 

MuseBar should show the song name, duration, play, skip, and pause buttons, the heart for liked tracks, and the volume button, which brings up settings. However, it shows the preferences, which usually show when pressing on the app's volume button. You can find a video example of this below **(please disregard the red flash, it comes from screen recording and has nothing to do with the issue)**.

https://user-images.githubusercontent.com/20716142/104246241-3e457b80-542b-11eb-8963-3c38e51bd69c.mp4

To reproduce this behavior: 

• Open MuseBar 
• **(Optional)** Restart ```OSDUIHelper``` within Activity Monitor 

**Error 2: Restarting MuseBar solves most issues but removes MuseBar from the control strip** 

Expected behavior: 

MuseBar should show the play and pause button over the album artwork of the current song on the Control Strip, but it doesn't show up on the control strip at all. After a few closes or restarts of the app, it  _sometimes_ shows up but not often. A video of this error can be found below as well.

https://user-images.githubusercontent.com/20716142/104246235-3c7bb800-542b-11eb-9d42-eb02a3cf9e74.mp4

To reproduce this behavior: 

• Open MuseBar 
• Hopefully run into the bug from Error 1
• Restart MuseBar
• Press and hold on MuseBar's Control Strip

———

Let me know if there's anything you need from me to help diagnose this. Thanks!

**Comment by planecore** [comment]
Hey! Sorry I'm responding late, I got COVID and needed to rest.

Do you use Spotify or Apple Music?
About bug 1, with Apple Music I show the preferences immediately because of system limitations.

I could reproduce bug 2 and I'm working on a fix.

**Comment by 3raxton** [comment]
Hey there,

No worries, I've also had it and understand what's needed. Please, take your time. I use Spotify, both of these come from Spotify. 

It's interesting you mention the preferences for Apple Music. Would the first bug be expected behavior for Spotify as well?

Thanks!

**Comment by planecore** [comment]
The first bug wouldn't be expected behavior for Spotify, only for Apple Music. I'll look into it.

**Comment by 3raxton** [comment]
Appreciate it!

**Comment by owellsjr** [comment]
@planecore Just wanted to chime in and say that I'm experiencing similar issues. I stumbled upon this after becoming disillusioned with the sheer complexity of Better Touch Tool when all I really want is a Now Playing widget that isn't useless. Other than that I actually like the built in Touch Bar. So I was very excited to see that this app essentially does just that. I installed it a hour or so ago and I've been tinkering with it but it refuses to to display this widget at all.

**Comment by mouhstach007** [comment]
Hi I'm experiencing the same issue installing your promising app on macOS Big Sur 11.3.1 with Apple Music : I've seen you haven't made any update since then : as you were talking about investigation, do you think it could be solvable or do you throw in the towel ;) ? thanks !

**Comment by mmbento** [comment]
I installed it today and it worked fine for 1 hour. Right now it only shows the preference panel with Apple Music. Is there any way to resolve this bug?

**Comment by owellsjr** [comment]
Unfortunately this app is fundamentally broken in its current state when using it with **Apple Music**. But there is a workaround ...

1. Play any track in the Spotify app.
2. Launch MuseBar. The main screen should show because it works with Spotify.
3. Pause Spotify.
4. Play your desired track in Apple Music. The main screen should continue to show and work as expected.

It's cumbersome I know. But it will get you going until @planecore is able to get a fix in place.
